In [1]:
import selenium.webdriver
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from urllib import request
import bs4
import re
import pandas as pd

In [2]:
http='https://fr.wikipedia.org/wiki/%C3%89lection_pr%C3%A9sidentielle_en_France#R%C3%A9sultats_depuis_1965'
request_text = request.urlopen(http).read()
page = bs4.BeautifulSoup(request_text, "lxml")
print(page.title)

<title>Élection présidentielle en France — Wikipédia</title>

In [3]:
(table1,table2)=page.find_all("table",attrs={'class':'wikitable'})

In [4]:
#2002=9

In [5]:
res={'candidats':[],'résultats':[],'partis':[],'année':[]}
elections=table1.find_all('tr')[8:]
for l in range(len(elections)):
    test=elections[l].find_all('td')
    annee=int(test[0].text.strip())
    for j in range(1,len(test)-1):
        sub_test=test[j]#.text#find_all('a')
        a=sub_test.find_all('a')
        if 'soutien' in sub_test.text:
            line1=a[1].get('title')
            line2=a[2].get('title')
            res['partis'].append((re.sub(r'\(.*?\)', '',line1).strip(),re.sub(r'\(.*?\)', '',line2).strip()))
            res['année'].append(annee)
        else:
            for i in range(1,len(a),2):
                line=a[i].get('title')
                res['partis'].append(re.sub(r'\(.*?\)', '',line).strip())
                
                res['année'].append(annee)
        for i in sub_test.text.split('%'):
            i=i.strip()
            if i!='':
                if '(' in i:
                    i=re.split(r'\(.*?\)',i)
                else:
                    i=i.split()
                if i[0]=='Bové':
                    continue
                res['candidats'].append(i[0].strip())
               
                res['résultats'].append(float(i[1].replace(',','.')))

In [6]:
df=pd.DataFrame(res)

In [7]:
df

,candidats,résultats,partis,année
0,Laguiller,5.72,Lutte ouvrière,2002
1,Besancenot,4.25,Ligue communiste révolutionnaire,2002
2,Gluckstein,0.47,Parti des travailleurs,2002
3,Hue,3.37,Parti communiste français,2002
4,Jospin,16.18,Parti socialiste,2002
5,Chevènement,5.33,Mouvement des citoyens,2002
6,Taubira,2.32,Parti radical de gauche,2002
7,Mamère,5.25,Les Verts,2002
8,Lepage,1.88,Cap21,2002
9,Bayrou,6.84,Union pour la démocratie française,2002
10,Chirac,19.88,Rassemblement pour la République,2002
11,Madelin,3.91,Démocratie libérale,2002
12,Boutin,1.19,Forum des républicains sociaux,2002
13,JM Le Pen,16.86,Rassemblement national,2002
14,Mégret,2.34,Mouvement national républicain,2002
15,Saint-Josse,4.23,"Chasse, pêche, nature et traditions",2002
16,Besancenot,4.08,Ligue communiste révolutionnaire,2007
17,Laguiller,1.33,Lutte ouvrière,2007
18,Schivardi,0.34,Parti des travailleurs,2007
19,Buffet,1.93,Parti communiste français,2007
20,Royal,25.87,Parti socialiste,2007
21,Voynet,1.57,Les Verts,2007
22,Bayrou,18.57,Union pour la démocratie française,2007
23,Sarkozy,31.18,Union pour un mouvement populaire,2007
24,Villiers,2.23,Mouvement pour la France,2007
25,JM Le Pen,10.44,Rassemblement national,2007
26,Nihous,1.15,"Chasse, pêche, nature et traditions",2007
27,Poutou,1.15,Nouveau Parti anticapitaliste,2012
28,Arthaud,0.56,Lutte ouvrière,2012
29,Mélenchon,11.10,Front de gauche,2012
30,Hollande,28.63,Parti socialiste,2012
31,Joly,2.31,Europe Écologie Les Verts,2012
32,Bayrou,9.13,Mouvement démocrate,2012
33,Sarkozy,27.18,Union pour un mouvement populaire,2012
34,Dupont-Aignan,1.79,Debout la France,2012
35,M Le Pen,17.90,Rassemblement national,2012
36,Cheminade,0.25,Solidarité et progrès,2012
37,Poutou,1.09,Nouveau Parti anticapitaliste,2017
38,Arthaud,0.64,Lutte ouvrière,2017
39,Mélenchon,19.58,"(La France insoumise, Parti communiste français)",2017
40,Hamon,6.36,"(Parti socialiste, Europe Écologie Les Verts)",2017
41,Macron,24.01,"(La République en marche, Mouvement démocrate)",2017
42,Fillon,20.01,Les Républicains,2017
43,Dupont-Aignan,4.70,Debout la France,2017
44,M Le Pen,21.30,Rassemblement national,2017
45,Lassalle,1.21,Résistons,2017
46,Asselineau,0.92,Union populaire républicaine,2017
47,Cheminade,0.18,Solidarité et progrès,2017
48,Poutou,0.77,Nouveau Parti anticapitaliste,2022
49,Arthaud,0.56,Lutte ouvrière,2022
50,Mélenchon,21.95,La France insoumise,2022
51,Roussel,2.28,Parti communiste français,2022
52,Hidalgo,1.75,Parti socialiste,2022
53,Jadot,4.63,Europe Écologie Les Verts,2022
54,Macron,27.85,"(La République en marche, Mouvement démocrate)",2022
55,Pécresse,4.78,Les Républicains,2022
56,Dupont-Aignan,2.06,Debout la France,2022
57,M Le Pen,23.15,Rassemblement national,2022
58,Zemmour,7.07,Reconquête,2022
59,Lassalle,3.13,Résistons,2022

In [8]:
t2=table2.find_all('tr')[7:]
tour2={}
for years in t2:
    year=years.find_all('td')
    annee=int(year[0].text)
    for j in year[1:]:
        if '-' in j.text:
            continue
        else:
            candidat=''
            resultat=''
            c=0
            
            while not j.text[c].isnumeric():
                candidat+=j.text[c]
                c+=1
            resultat=j.text[c:c+5]
            resultat=float(resultat.replace(',','.'))
            candidat=candidat.strip()
            tour2[(annee,candidat)]=resultat
            

print(tour2)

{(2002, 'Chirac'): 82.21, (2002, 'JM Le Pen'): 17.79, (2007, 'Royal'): 46.94, (2007, 'Sarkozy'): 53.06, (2012, 'Hollande'): 51.64, (2012, 'Sarkozy'): 48.36, (2017, 'Macron'): 66.1, (2017, 'M Le Pen'): 33.9, (2022, 'Macron'): 58.55, (2022, 'M Le Pen'): 41.45}

In [9]:
df['second tour']=0

In [ ]:
for i,j in zip(df['année'],df['candidats']):
    
    if (i,j) in tour2.keys():
        
        df.loc[(df['année']==i) & (df['candidats']==j),'second tour']=tour2[(i,j)]

2002 Chirac
2002 JM Le Pen
2007 Royal
2007 Sarkozy
2012 Hollande
2012 Sarkozy
2017 Macron
2017 M Le Pen
2022 Macron
2022 M Le Pen

C:\Users\math\AppData\Local\Temp\ipykernel_18620\52737916.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '82.21' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[(df['année']==i) & (df['candidats']==j),'second tour']=tour2[(i,j)]

In [27]:
df

,candidats,résultats,partis,année,second tour
0,Laguiller,5.72,Lutte ouvrière,2002,0.00
1,Besancenot,4.25,Ligue communiste révolutionnaire,2002,0.00
2,Gluckstein,0.47,Parti des travailleurs,2002,0.00
3,Hue,3.37,Parti communiste français,2002,0.00
4,Jospin,16.18,Parti socialiste,2002,0.00
5,Chevènement,5.33,Mouvement des citoyens,2002,0.00
6,Taubira,2.32,Parti radical de gauche,2002,0.00
7,Mamère,5.25,Les Verts,2002,0.00
8,Lepage,1.88,Cap21,2002,0.00
9,Bayrou,6.84,Union pour la démocratie française,2002,0.00
10,Chirac,19.88,Rassemblement pour la République,2002,82.21
11,Madelin,3.91,Démocratie libérale,2002,0.00
12,Boutin,1.19,Forum des républicains sociaux,2002,0.00
13,JM Le Pen,16.86,Rassemblement national,2002,17.79
14,Mégret,2.34,Mouvement national républicain,2002,0.00
15,Saint-Josse,4.23,"Chasse, pêche, nature et traditions",2002,0.00
16,Besancenot,4.08,Ligue communiste révolutionnaire,2007,0.00
17,Laguiller,1.33,Lutte ouvrière,2007,0.00
18,Schivardi,0.34,Parti des travailleurs,2007,0.00
19,Buffet,1.93,Parti communiste français,2007,0.00
20,Royal,25.87,Parti socialiste,2007,46.94
21,Voynet,1.57,Les Verts,2007,0.00
22,Bayrou,18.57,Union pour la démocratie française,2007,0.00
23,Sarkozy,31.18,Union pour un mouvement populaire,2007,53.06
24,Villiers,2.23,Mouvement pour la France,2007,0.00
25,JM Le Pen,10.44,Rassemblement national,2007,0.00
26,Nihous,1.15,"Chasse, pêche, nature et traditions",2007,0.00
27,Poutou,1.15,Nouveau Parti anticapitaliste,2012,0.00
28,Arthaud,0.56,Lutte ouvrière,2012,0.00
29,Mélenchon,11.10,Front de gauche,2012,0.00
30,Hollande,28.63,Parti socialiste,2012,51.64
31,Joly,2.31,Europe Écologie Les Verts,2012,0.00
32,Bayrou,9.13,Mouvement démocrate,2012,0.00
33,Sarkozy,27.18,Union pour un mouvement populaire,2012,48.36
34,Dupont-Aignan,1.79,Debout la France,2012,0.00
35,M Le Pen,17.90,Rassemblement national,2012,0.00
36,Cheminade,0.25,Solidarité et progrès,2012,0.00
37,Poutou,1.09,Nouveau Parti anticapitaliste,2017,0.00
38,Arthaud,0.64,Lutte ouvrière,2017,0.00
39,Mélenchon,19.58,"(La France insoumise, Parti communiste français)",2017,0.00
40,Hamon,6.36,"(Parti socialiste, Europe Écologie Les Verts)",2017,0.00
41,Macron,24.01,"(La République en marche, Mouvement démocrate)",2017,66.10
42,Fillon,20.01,Les Républicains,2017,0.00
43,Dupont-Aignan,4.70,Debout la France,2017,0.00
44,M Le Pen,21.30,Rassemblement national,2017,33.90
45,Lassalle,1.21,Résistons,2017,0.00
46,Asselineau,0.92,Union populaire républicaine,2017,0.00
47,Cheminade,0.18,Solidarité et progrès,2017,0.00
48,Poutou,0.77,Nouveau Parti anticapitaliste,2022,0.00
49,Arthaud,0.56,Lutte ouvrière,2022,0.00
50,Mélenchon,21.95,La France insoumise,2022,0.00
51,Roussel,2.28,Parti communiste français,2022,0.00
52,Hidalgo,1.75,Parti socialiste,2022,0.00
53,Jadot,4.63,Europe Écologie Les Verts,2022,0.00
54,Macron,27.85,"(La République en marche, Mouvement démocrate)",2022,58.55
55,Pécresse,4.78,Les Républicains,2022,0.00
56,Dupont-Aignan,2.06,Debout la France,2022,0.00
57,M Le Pen,23.15,Rassemblement national,2022,41.45
58,Zemmour,7.07,Reconquête,2022,0.00
59,Lassalle,3.13,Résistons,2022,0.00

In [28]:
df.to_csv('pres.csv',index=False)