In [43]:
import pandas as pd
import numpy as np
import re

Ce notebook permet de netoyer le dataset sur les députés et de le fusionner avec celui sur les donnés financiers

In [44]:
dep=pd.read_csv('deputes/deputes.csv')
fin=pd.read_csv('compte_partis/finances08_22.csv')
pres=pd.read_csv('pres.csv')

In [45]:
for i in fin['nom parti'].unique():
    print(i)

DEMOCRATIE ET REPUBLIQUE (anciennement Metz pour tous)
L'alliance régionale
Centre national des Indépendants et Paysans
COMBAT POUR LES VALEURS
FRONT NATIONAL
Génération écologie - Les Bleus
GROUPEMENT FRANCE-RÉUNION
LE TRÈFLE-LES NOUVEAUX                                                                                    ÉCOLOGISTES-HOMME NATURE ANIMAUX
PARTI RADICAL DE GAUCHE
ARIAS 94
Mouvement d'union de gestion communale de la ville de Plan de Cuques
PARTI COMMUNISTE FRANÇAIS
UNION POUR L'AVENIR DE PLOERMEL
Parti communiste guadeloupéen
PARTI COMMUNISTE MARTINIQUAIS
PARTI COMMUNISTE REUNIONNAIS
Parti progressiste Martiniquais
Parti radical
PARTI SOCIALISTE
CHASSE PÊCHE NATURE TRADITIONS
PARTI SOCIALISTE GUYANAIS
PARTIT OCCITAN
Union démocrate bretonne
UNION POUR LA DÉMOCRATIE FRANÇAISE
LUTTE OUVRIÈRE
Union pour le pays Malouin
UNION RÉPUBLICAINE LORRAINE
LES VERTS
PARTI DES TRAVAILLEURS
Energie France
SOLIDARITE ÉCOLOGIE GAUCHE ALTERNATIVE
Tahoeraa Huiraatira
MOUVEMENT RÉPUBLICAIN ET CITOYEN
Mouvement indépendaniste Martiniquais
MOUVEMENT DES RÉFORMATEURS
ARCHIPEL DEMAIN
L'ACTION
Comité des citoyens montreuillois
ASSOCIATION PARTI SOCIALISTE - PARTI RADICAL DE GAUCHE ET APPARENTÉS
Mouvement Pour la France
AIMER ANGERS
MOUVEMENT ÉCOLOGISTE INDÉPENDANT
Rassemblement UMP pour la Calédonie dans la république
LA VOLONTÉ DE VIVRE ENSEMBLE
Mouvement démocratique Alsacienne
DÉMOCRATIE ET LIBERTÉ
Parti Bonapartiste
Confédération des écologistes indépendants
Union du peuple Alsacien
LIGUE COMMUNISTE RÉVOLUTIONNAIRE
ASSOCIATION POUR LA RÉFORME
RASSEMBLER POUR AGIR
Comité de soutien à Patrick Bobet
Solidarité et progrès
TOULOUSE POUR TOUS
Francheville au cœur
ASSOCIATION PARIS 15
ASSOCIATION POUR LA DÉMOCRATIE L'ÉCOLOGIE ET LA SOLIDARITÉ
Fetia Api
FUTURS-MOUVEMENT DES REFONDATEURS COMMUNISTES
GUADELOUPE UNIE SOCIALISME ET RÉALITÉS
ISÈRE PREMIÈRE
ALLIANCE MÉDITERRANÉE ALPES
Argenteuil que nous aimons
CONVERGENCES-GILLES CARREZ
UNION POUR LA VIIÈME
Réussir ensemble en Dordogne-Périgord
UNION POUR L'AVENIR DE MANTES-LA-JOLIE
UNION POUR L'AVENIR DU XVIÈME SUD
CONVERGENCES CHAMPIGNY
France moderne
UNION POUR L'ALBIGEOIS
MOUVEMENT HOMMES-NATURE ANIMAUX
UNION POUR MURET
Savoie d'aujourd'hui
AGIR AU QUOTIDIEN AVEC NICOLAS DUPONT-AIGNAN
Pour l'Aquitaine
DROITE SOCIALE
Mouvement liberal Martiniquais
ENSEMBLE POUR LA France
GROUPE D'ÉTUDES MUNICIPALES D'EURE ET LOIR
Participation et liberté
LES ALTERNATIFS
Union pour la Savoie
UNION POUR SAINT SÉBASTIEN SUR LOIRE
PARTI GAULLISTE
Rassemblement des contribuables français
MOUVEMENT NATIONAL RÉPUBLICAIN
DÉMOCRATIE CHRÉTIENNE FRANÇAISE
TARBES 2008
ENSEMBLE POUR GONESSE
RASSEMBLEMENT POUR LA FRANCE ET L'INDÉPENDANCE DE L'EUROPE
Union pour Chatillon
Droite Libérale-Chrétienne
COMITÉ D'ACTION ET DE RÉFLEXION DÉPARTEMENTALE
VIVRE A LUISANT
FONSORBÈS CITOYENNETÉ
LA RESTAURATION NATIONALE
ASSOCIATION 6ÈME UNION
L'action avec Gilbert Meyer
L'idée française
Agir pour demain
Mouvement des Seine et Marnais
COTELEC
LA FRANCE EN TÊTE
Idées-force
ENTENTE CITOYENNE
UNION RÉPUBLICAINE ET D'ACTIONS COMMUNAUTAIRES
VIVRE À SCHOELCHER
MOUVEMENT POPULAIRE FRANCISCAIN
Forum des républicains sociaux
RASSEMBLEMENT POUR L'ESSONNE
CITOYENNETÉ ACTION PARTICIPATION POUR LE 21ÈME SIÈCLE
Rassemblement pour Levallois
GRENOBLE EST À VOUS
FRANCE.9
COMITÉ POUR SAINT-MICHEL
Savoie  plus loin
Association de soutien à l'action de Nicolas Sarkozy
PARTI POUR LA LIBÉRATION DE LA MARTINIQUE
UNION POUR STRASBOURG
Chatenay Malabry à pleine vie
VIENNE AVENIR
LES AMIS DE RICHARD MALLIÉ
Régions et peuples solidaires
CONVENTION CITOYENNE
Unoin des victimes de l'état
Participation citoyenne
DROIT DE CHASSE
ASSOCIATION POUR L'AVENIR DE LA HAUTE SAINTONGE ET DE LA SAINTONGE ATLANTIQUE
CAP SUR L'AVENIR 13
IDENTITÉ ET RÉPUBLIQUE
UMP
Rassemblement pour l'indépendance et la souveraineté de la France
Réunion avenir une ambition pour la Réunion dans la France
DEBOUT LA RÉPUBLIQUE
Agir ensemble pour Levallois
ACTION SAVOIE PREMIÈRE
LA RELÈVE
PARTITU DI A NAZIONE CORSA
ALLIANCE ROYALE
FORUM EUROPÉEN CLERMONT-FERRAND AUVERGNE
UNION DES SOCIALISTES POUR MIDI-PYRÉNÉES
Gauche citoyenne
DESSINONS L'AVENIR AVEC ALAIN GIRARD
Vivre l'union ensemble à SAINT-MANDÉ-VINCENNES-FONTENAY-SOUS-BOIS
PARIS DEMAIN
Batir le pays Martinique
VITRY RENOUVEAU
LA FRANCE EN ACTION
AUJOURD'HUI AUTREMENT
POUR PARIS
UNION POUR AIX
TE' AVEI' A
Non à la Turquie dans l'Europe
CHANGEONS VILLEURBANNE
MASSY POUR VOUS
UNION POUR LE VAL D'OISE
PARTI RÉPUBLICAIN CHRÉTIEN
Nouvelle donne
VIVRE MIEUX
PARTI POPULISTE- LA RELÈVE NATIONALE
NO OE E TE NUNA'A
Union pour le Val de Marne- Christian Cambon
BOUGEONS-NOUS
DIALOGUE & INITIATIVE
PARTI EUROPE DÉMOCRATIE ESPÉRANTO France
CHAMPIGNY CAP OUEST
Alternative libérale
RAUTAHI- Rassemblement pour la Polynésie Française
Toulouse avenir
UNIR POUR LYON AVEC LES ÉQUIPES DE CHARLES MILLION
IFRAP 2012
L'EURE D'AGIR
POUR UN PARIS GAGNANT
Désirs d'avenir
NOFWAP LA GUADELOUPE EN ACTION
RASSEMBLEMENT POUR LA SOLIDARITÉ ET LA DÉMOCRATIE
GÉNÉRATIONFRANCE.FR
Mouvement pour un renouveau politique
SAVOIE POUR TOUS
AGIR POUR L'ÉGALITÉ
MOUVEMENT CITOYEN DE LA RÉUNION
Rive droite
LE CHÊNE
Alternative Démocratie Socialisme
COMMUNISTES
LES AMIS DE MAX-ANDRÉ PICK
ASSOCIATION NATIONALE DES AMIS DE NICOLAS SARKOZY
Un avenir meilleur pour la population de la Réunion dans la France et dans l'Europe
RASSEMBLEMENT DÉMOCRATIQUE POUR LA MARTINIQUE
Courage République
PARTI DE GAUCHE
MARS - GAUCHE RÉPUBLICAINE
GAILLAC AU CŒUR
RASSEMBLEMENT DES CITOYENS POUR LA RÉPUBLIQUE
POUR PERTRUIS AUTREMENT
ALTERNATIVE 2007
VILLEURBANNE A TOUT CŒUR
MOUVEMENT DÉMOCRATE
NOUVEAU CENTRE
PARTI BRETON
Vivre ensemble pour leTarn
BIEN VIVRE DANS LE DROUAIS
LES PROGRESSISTES .FR
Union pour le changement à Cergy
ASSOCIATION MÛRS-ERIGNÉ, ENSEMBLE
ASSOCIATION DE SOUTIEN À L'ACTION D'ÉRIC WOERTH
Union pour l'Aveyron
NOUVEL OXYGÈNE
La gauche moderne
CAP SUR L'AVENIR
Rassemblement pour la Calédonie
PARTI LIBÉRAL DÉMOCRATE
TE MANA TOA- L'esprit du guerrier
Parti Socialiste Réunionnais
Alternance pour l'Île de France
MOUVEMENT CITOYEN RÉGIONAL NORD PAS DE CALAIS
O PORINETIA TO TATOU AI' A
SOLIDARITÉ – LIBERTÉ - JUSTICE ET PAIX
ROANNE PASSIONNÉMENT
LE MOUVEMENT
PARTI OUVRIER INDÉPENDANT
RASSEMBLEMENT POUR UNE EUROPE ÉCOLOGISTE
CONVERGENCES NATIONALES
TIATAU
DÉMOCRATIE ET RÉPUBLIQUE
AI'A.-API "TERRE NOUVELLE"
CENTRE NATIONAL DES INDÉPENDANTS ET PAYSANS
LE TRÈFLE-LES NOUVEAUX ÉCOLOGISTES-HOMME NATURE ANIMAUX
PARTI COMMUNISTE RÉUNIONNAIS
PARTI RADICAL
UNION DÉMOCRATIQUE BRETONNE
l'UNION POUR LA DÉMOCRATIE FRANÇAISE
UNION POUR LE PAYS MALOUIN
VERTS
TAVINI HUIRAATIRA NO TE AO MA'OHI (FRONT DE LIBÉRATION DE POLYNÉSIE)
TAHOERAA HUIRAATIRA
MOUVEMENT INDÉPENDANTISTE MARTINIQUAIS
COMITÉ DES CITOYENS MONTREUILLOIS
Association parti socialiste parti radical de gauche et apparentés
MOUVEMENT DÉMOCRATIE ALSACIENNE
l'ASSOCIATION DÉMOCRATIE ET LIBERTÉ
PARTI BONAPARTISTE
UNSER LAND
FRANCHEVILLE AU COEUR
l'ASSOCIATION POUR LA DÉMOCRATIE L'ÉCOLOGIE ET LA SOLIDARITÉ
ARGENTEUIL QUE NOUS AIMONS
l'UNION POUR L'AVENIR DU XVIÈME SUD
l'UNION POUR L'ALBIGEOIS
MOUVEMENT HOMMES-ANIMAUX-NATURE
SAVOIE D'AUJOURD'HUI
d'AGIR AU QUOTIDIEN AVEC NICOLAS DUPONT-AIGNAN
POUR L'AQUITAINE
la DROITE SOCIALE
ENSEMBLE POUR LA FRANCE
RASSEMBLEMENT DES CONTRIBUABLES FRANÇAIS
VIVRE À LUISANT
FONSORBÈS CITOYENNETÉ 2000
l'ASSOCIATION 6ÈME UNION
L'IDÉE FRANÇAISE
IDÉES-FORCE
l'ENTENTE CITOYENNE
PARTI CHRÉTIEN-DÉMOCRATE
RASSEMBLEMENT POUR LEVALLOIS
France.9
CHATENAY MALABRY À PLEINE VIE
RÉGIONS ET PEUPLES SOLIDAIRES
l'UNION DES VICTIMES DE L'ÉTAT SOS - SENIORS
RASSEMBLEMENT POUR L'INDÉPENDANCE ET LA SOUVERAINETÉ DE LA France
RÉUNION AVENIR UNE AMBITION POUR LA RÉUNION DANS LA France
AGIR ENSEMBLE POUR LEVALLOIS
l'UNION DES SOCIALISTES POUR MIDI-PYRÉNÉES
la GAUCHE CITOYENNE
VIVRE L'UNION ENSEMBLE À SAINT-MANDÉ-VINCENNES-FONTENAY-SOUS-BOIS
TE'AVEI'A
NOUVELLE DONNE
ALTERNATIVE LIBÉRALE
RAUTAHI -  RASSEMBLEMENT POUR LA POLYNÉSIE FRANÇAISE
ALTERNATIVE DÉMOCRATIE SOCIALISME
UN AVENIR MEILLEUR POUR LA POPULATION DE LA RÉUNION DANS LA FRANCE ET DANS L'EUROPE
POUR PERTUIS AUTREMENT
VILLEURBANNE À TOUT CŒUR
O PORINETIA TO TATOU AI'A
LA GAUCHE MODERNE
RASSEMBLEMENT POUR LA CALÉDONIE
SOLIDARITÉ - LIBERTÉ, JUSTICE ET PAIX
ÉCOUTER POUR AGIR
PARTI DE LA France
GROUPE POLITIQUE L'AVENIR ENSEMBLE
l'ASSOCIATION DE SOUTIEN A L'ACTION DE JEAN FRANÇOIS LAMOUR
GAILLAC SOLIDAIRE
la GAUCHE UNITAIRE
LA FÉDÉRATION DE CITOYEN-NE-S ET DE FORCES POUR UNE ALTERNATIVE SOCIALE ET ÉCOLOGIQUE
TOURCOING EN VALEUR
POUR MULHOUSE
MAIZIÈRES ENSEMBLE
L'ALLIANCE RÉGIONALE
GÉNÉRATION ÉCOLOGIE - LES BLEUS
MOUVEMENT D'UNION DE GESTION COMMUNALE DE LA VILLE DE PLAN DE CUQUES
PARTI COMMUNISTE FRANCAIS
l'UNION POUR L'AVENIR DU PAYS DE PLOERMEL
PARTI COMMUNISTE GUADELOUPÉEN
PARTI PROGRESSISTE MARTINIQUAIS
CHASSE PÊCHE NATURE ET TRADITIONS
ÉNERGIE France
SOLIDARITÉ ÉCOLOGIE GAUCHE ALTERNATIVE
WALWARI
MOUVEMENT POUR LA FRANCE
RASSEMBLEMENT UMP (RASSEMBLEMENT POUR LA CALÉDONIE DANS LA RÉPUBLIQUE)
CONFÉDÉRATION DES ÉCOLOGISTES INDÉPENDANTS
l'ASSOCIATION POUR LA RÉFORME
COMITÉ DE SOUTIEN À PATRICK BOBET
SOLIDARITÉ ET PROGRÈS
l'ASSOCIATION PARIS 15
FETIA API
l'ALLIANCE MÉDITERRANÉE ALPES (LES AMIS DE CHRISTIAN ESTROSI)
l'UNION POUR LA VIIÈME
RÉUSSIR ENSEMBLE EN DORDOGNE PÉRIGORD
l'UNION POUR L'AVENIR DE MANTES-LA-JOLIE
FRANCE MODERNE
l'UNION POUR MURET
MOUVEMENT LIBERAL POPULAIRE
CHATEAUDUN ACTIONS RENOUVEAU
PARTICIPATION ET LIBERTÉ
l'UNION POUR LA SAVOIE
l'UNION POUR SAINT SÉBASTIEN SUR LOIRE
MOUVEMENT DEPARTEMENTALISTE MAHORAIS
l'UNION POUR CHATILLON
AGIR POUR DEMAIN
MOUVEMENT DES SEINE-ET-MARNAIS
l'UNION RÉPUBLICAINE ET D'ACTIONS COMMUNAUTAIRES
CITOYENNETÉ ACTION PARTICIPATION POUR LE  21ÈME SIÈCLE
GRENOBLE EST A VOUS
SAVOIE PLUS LOIN
l'ASSOCIATION DE SOUTIEN À L'ACTION DE NICOLAS SARKOZY
l'UNION POUR STRASBOURG
DES AMIS DE RICHARD MALLIÉ
PARTICIPATION CITOYENNE
l'ASSOCIATION POUR L'AVENIR DE LA HAUTE SAINTONGE ET DE LA SAINTONGE ATLANTIQUE
l'UNION POUR UN MOUVEMENT POPULAIRE
BÂTIR LE PAYS MARTINIQUE
NON À LA TURQUIE DANS L'EUROPE
PARTI POPULISTE - LA RELÈVE NATIONALE
BOUGEONS NOUS
TOULOUSE AVENIR
NOFWAP, LA GUADELOUPE EN ACTION
MOUVEMENT POUR UN RENOUVEAU POLITIQUE
RIVE DROITE
Le CHÊNE
les AMIS DE MAX-ANDRÉ PICK
l'ASSOCIATION NATIONALE DES AMIS DE NICOLAS SARKOZY
RÉPUBLIQUE SOLIDAIRE (COURAGE RÉPUBLIQUE)
Association PSLE - NOUVEAU CENTRE
VIVRE ENSEMBLE POUR LE TARN
LES PROGRESSISTES.FR
l'ASSOCIATION MÛRS-ERIGNÉ, ENSEMBLE
l'ASSOCIATION DE SOUTIEN À L'ACTION D'ÉRIC WOERTH
L'UNION POUR L'AVEYRON
TE MANA TOA - L'ESPRIT DU GUERRIER
PARTI SOCIALISTE RÉUNIONNAIS
ALTERNANCE POUR L'ILE DE France
AGIR ENSEMBLE
OSONS LE DYNAMISME POUR LOUVECIENNES (dit  OSONS)
CHANGER C'EST POSSIBLE
l'UNION ÉLARGIE DES SENIORS
l'UNION DES NON INSCRITS
SAINT-MICHEL-GAUCHE-AVENIR
NOUVEAU PARTI ANTICAPITALISTE
MOUVEMENT SOCIAL ET LIBÉRAL DE NORMANDIE
l'ÉVOLUTION SOCIALE DÉMOCRATE
l'ASSOCIATION DES OBJECTEURS DE CROISSANCE
CHANGER POUR GAGNER
CENTRE DÉMOCRATE
PARTI DE LA RÉSISTANCE
l'ALLIANCE CENTRISTE
MOUVEMENT UNITAIRE PROGRESSISTE
A GAUCHE BESOIN D'OPTIMISME
ALLIANCE RÉGIONALE
EUROPE ÉCOLOGIE LES VERTS
ASSOCIATION DÉMOCRATIE ET LIBERTÉ
ALLIANCE MÉDITERRANÉE ALPES (LES AMIS DE CHRISTIAN ESTROSI)
ENTENTE RÉPUBLICAINE-LE PARTI AZURÉEN
CHÂTEAUDUN ACTIONS RENOUVEAU
UNION POUR LA SAVOIE
L'AVENIR ENSEMBLE (Vivre à Luisant)
ASSOCIATION DE SOUTIEN À L'ACTION DE NICOLAS SARKOZY
UNION DES VICTIMES DE L'ÉTAT SOS - SENIORS
UNION POUR UN MOUVEMENT POPULAIRE
RÉUNION AVENIR UNE AMBITION POUR LA RÉUNION DANS LA FRANCE
GAUCHE CITOYENNE
PARTI EUROPE DÉMOCRATIE ESPÉRANTO FRANCE
AVENIR MEILLEUR POUR LA POPULATION DE LA RÉUNION DANS LA FRANCE ET DANS L'EUROPE
RÉPUBLIQUE SOLIDAIRE
ASSOCIATION PSLE - NOUVEAU CENTRE
UNION POUR L'AVEYRON
LA DROITE SOCIALE (NOUVEL OXYGÈNE)
PARTI DE LA FRANCE
UNION ÉLARGIE DES SENIORS
ASSOCIATION DE SOUTIEN A L'ACTION DE JEAN FRANÇOIS LAMOUR
UNION DES NON INSCRITS
GAUCHE UNITAIRE
ASSOCIATION DES OBJECTEURS DE CROISSANCE
ALLIANCE CENTRISTE
BLOC IDENTITAIRE - MOUVEMENT SOCIAL EUROPEEN
ENSEMBLE POUR LA 7ème
MOUVEMENT POLITIQUE D’ÉDUCATION POPULAIRE
ENSEMBLE, REDRESSONS LA FRANCE
PALAISEAU A VENIR
ASSOCIATION DE SOUTIEN A L'ACTION DE BENOIST APPARU
ALLIANCE POPULAIRE POUR LE CALAISIS
GénérationS Asnières
NOUVELLE UNION FRANCAISE
ROUGE BANLIEUE, LES PRODUCTEURS DE VILLE EN SEINE-SAINT-DENIS
LE 10e EN MOUVEMENT
AGIR POUR COLOMBES
A STRASBOURG
RASSEMBLEMENT POUR LA FRANCE
Union Gaulliste Sociale pour les Colombiens "UGASCO"
LE MOUVEMENT DE LA DIVERSITÉ
RASSEMBLEMENT RESPECT RÉUNION RRR
LE XII SOLIDAIRE
UNION RÉPUBLICAINE POPULAIRE (U.R.P.)
UNION CENTRISTE DÉMOCRATE
OSONS MIDI-PYRÉNÉES
LIGUE DU SUD
MOUVEMENT INDÉPENDANT POPULAIRE - MIP
PARTI SOCIALISTE GUADELOUPÉEN
"CAR" CHÂTEAUDUN ACTIONS RENOUVEAU
UNION POUR CHATILLON
L'AVENIR ENSEMBLE
UNION DES VICTIMES DE L'ÉTAT - SOS SÉNIORS
ASSOCIATION POUR L'AVENIR DE LA HAUTE SAINTONGE ET DE LA SAINTONGE ATLANTIQUE
RASSEMBLEMENT POUR L'INDÉPENDANCE ET LA SOUVERAINETÉ DE LA FRANCE
ENSEMBLE CROSNE ENCORE ET TOUJOURS
UNION POUR LE VAL DE MARNE - CHRISTIAN CAMBON
LA DROITE SOCIALE
ACTION ILE-DE-FRANCE
LE PARTI DE LA FRANCE
UNION POUR LA DEMOCRATIE ET LA PROSPERITE
SAINT-MICHEL GAUCHE AVENIR
PARTI ANTI-SIONISTE
BLOC IDENTITAIRE
A GAUCHE, BESOIN D'OPTIMISME
AVENIR SUD 77
RENOUVEAU FRANCAIS
FRANCE ÉNERGIES
VILLENEUVE PASSION
JEANNE
DES IDÉES ET DES REVES
PARTI DES LIBERTÉS
NOGENT DÉMOCRATIE
LES CENTRISTES HUMANISTES
AMBITION CITOYENNE ET SOLIDAIRE POUR L'YONNE
100% ASNIERES
PARIS 2014
MOUVEMENT UNITAIRE DES DROITES INDÉPENDANTES (MUDI)
LE BON SENS EN PUISAYE
NICOLAS HULOT 2012
ACU ASSOCIATION DES COMMUNISTES UNITAIRES
LA DIAGONALE
RASSEMBLEMENT POUR LA GUADELOUPE
FRANCE ÉCOLOGIE
O COMME OXYGÈNE
ESPRIT NEUF
L'AUTRE MÉTROPOLE
PARTI PIRATE
INITIATIVES DIJON
RÉPONDRE À GAUCHE AVEC FRANÇOIS HOLLANDE
ASSOCIATION POUR LA PROMOTION DE LA CANDIDATURE DE MARTINE AUBRY AUX PRIMAIRES OUVERTES PAR LE PARTI SOCIALISTE POUR LA DÉSIGNATION À L'ÉLECTION PRÉSIDENTIELLE DE 2012
LA FORCE CITOYENNE
MARSEILLE 21
TERRITOIRES EN MOUVEMENT
ASSOCIATION FRANCAIS DE L'ÉTRANGER - CITOYENS EN MOUVEMENT
UNION DE LA MAJORITÉ MUNICIPALE
CENTRE HUMANISTE EUROPÉEN
ACTION TANK
COMITÉ CENTRAL BONAPARTISTE
LE RASSEMBLEMENT (LES AMIS DE CHRISTIAN ESTROSI)
MURET AU CŒUR
TARBES 2014
MIEUX VIVRE ENSEMBLE
FORCE RÉPUBLICAINE
ENSEMBLE, CROSNE, ENCORE ET TOUJOURS
L'ALLIANCE ÉCOLOGISTE INDÉPENDANTE
UNION POUR LA FRANCE
FORUM DÉMOCRATIQUE
Savoie pour tous
UNION POUR LA DÉMOCRATIE ET LA PROSPÉRITÉ
LES AMIS DE NICOLAS SARKOZY
MOUVEMENT LIBÉRAL POPULAIRE
UNION POUR SAINT-SÉBASTIEN-SUR-LOIRE
MOUVEMENT CITOYEN RÉGIONAL NORD-PAS-DE-CALAIS
ASSOCIATION DE SOUTIEN À L'ACTION DE JEAN FRANÇOIS LAMOUR
GÉNÉRATIONS ASNIERES
MOUVEMENT INDÉPENDANT POPULAIRE
ASSOCIATION DES COMMUNISTES UNITAIRES
APCMA
ASSOCIATION FRANÇAIS DE l'ÉTRANGER - CITOYENS EN MOUVEMENT
LA POLITIQUE AUTREMENT
COURANT DES POISSONS ROSES "CPR"
GRENOBLE 2014
POUR UNE NOUVELLE DÉMOCRATIE REPRÉSENTATIVE
ANGOULÊME AMBITION
GAUCHE ANTICAPITALISTE
ASSOCIATION CONSTRUIRE L'AVENIR
RIVE DROITE, RIVE GAUCHE, TOULOUSE LA MÉTROPOLE EUROPÉENNE
S.I.E.L. - SOUVERAINETÉ, INDÉPENDANCE ET LIBERTÉ
RÉPUBLIQUE, ÉCOLOGIE ET SOCIALISME 49
IA HAU NOA
POUR LA RÉUNION, DE TOUTES NOS FORCES
SAINT-CHAMOND AVANT TOUT
NOUVEAUX HORIZONS
LE GRAND PARIS DES CITOYENS
INDÉPENDANTS DE LA FRANCE DE MÉTROPOLE ET D'OUTRE-MER
LE CENTRE POUR LA FRANCE
PARTI MOUVEMENT BRETAGNE & PROGRÈS
FORCES MARTINIQUAISES DE PROGRÈS
POUR MARSEILLE 2014
RÉINVENTONS ASNIERES
L'AUTRE CHEMIN POUR LA GAUCHE
GÉNÉRATIONS VERNON, UN NOUVEAU SOUFFLE POUR NOTRE VILLE !
AVEC BLM
POUR VIVRE MIEUX EN SAVOIE
NANCY PREMIÈRE
FORCE EUROPÉENNE DÉMOCRATE
ASSOCIATION DES AMIS DE ERIC CIOTTI
ALTERNANCES PARISIENNES
ENTENTE RÉPUBLICAINE DE NICE
ENSEMBLE POUR LA ROCHELLE
LES AMIS DE NKM
PASSIONNÉMENT MARSEILLAIS
UNION DES DÉMOCRATES ET INDÉPENDANTS
GÉNÉRATIONS ANGOULEME
VIVEMENT DEMAIN
LA FRANCE DROITE
RASSEMBLEMENT POUR LE PEUPLE DE FRANCE
CHALON, ALTERNATIVE 2014
RASSEMBLEMENT POUR JOUÉ
VIVRE À SCEAUX
RASSEMBLEMENT RÉPUBLICAIN POUR LA FRANCE
FAÇONNONS VÉLIZY AUTREMENT
BEAUCHAMP RENOUVEAU
MIEUX VIVRE EN VAL D'OISE
ENSEMBLE POUR LYON
CALÉDONIE ENSEMBLE
FORCES DE GAUCHE
COMITE DE SOUTIEN A FRANCINE OCCIS
MOUVEMENT INITIATIVE POPULAIRE
UNION DES RADICAUX, CENTRISTES, INDÉPENDANTS ET DÉMOCRATES
UNION POUR LA DÉMOCRATIE
HERBLAY AVEC VOUS
LA MANUFACTURE
ANGERS 2014
ASNIÈRES DEBOUT
ENSEMBLE POUR NOGENT
CHAROLAIS BRIONNAIS EN MOUVEMENT
CHANGEONS NANTERRE POUR UNE VIE MEILLEURE
LIBERTE-EGALITE-MARSEILLAIS
RECONQUÊTE 18ème
AGIR PARIS - PARIS AU CENTRE
REFLAIXION
J'AIME LE 7ème
SOLIDARITÉ 21e, POUR UNE RECOMPOSITION VRAIMENT A GAUCHE DE LA GAUCHE EUROPEENNE
MOÛTIERS AUJOURD'HUI ET DEMAIN
MARSEILLE UNIE DU NORD AU SUD
MARSEILLE RASSEMBLÉE
L'ÉTOILE
LA DROITE FORTE
RESEAU-IDENTITES
MORBIHAN EN MOUVEMENT
LYON DIVERS DROITE
GÉNÉRATION MÂCON
BASSIN A CŒUR
POSSESSION ÉCOLOGIE SOLIDAIRE
ÉCRIVONS UNE NOUVELLE PAGE (E.N.P)
ASSOCIATION DE DÉFENSE DES SANARYENS
UNIS POUR VILLEURBANNE
MIEUX VIVRE A TASSIN LA DEMI-LUNE
MONTPELLIER AU CENTRE
FORCE D'AVENIR
UNION CITOYENNE POUR MONTPELLIER ET SES ENVIRONS
NKM PARIS 2014
LES AMIS DU MAIRE DE NICE
POUR SAINT-JEAN D'ILLAC
AVENIR SAINT JULIEN
PARTI SOCIALISTE DE GAUCHE
A TI'A PORINETIA - LE RASSEMBLEMENT DES POLYNÉSIENS
SOCIALISME EN PAYS SALONAIS
PARTI GRAND-CHARMONT AUTREMENT
CHANGEONS VAUJOURS
BONNE RÉPUBLIQUE
MOUVEMENT POPULAIRE CALEDONIEN
LE RASSEMBLEMENT CITOYEN
NOUS CITOYENS
OBJECTIF REUNION
ECOLOGIE IVRY-SEINE AMONT
RASSEMBLER POUR UNE ILE VIVANTE
BREIZH EUROPA
LE CAP AJ POUR LA FRANCE
UNION POUR UN MOUVEMENT POPULAIRE (LES RÉPUBLICAINS)
DEBOUT LA FRANCE
MOUVEMENT POLITIQUE D'ÉMANCIPATION POPULAIRE
RENOUVEAU FRANÇAIS
LE PHARE (PROMOTION DE L'HUMANISME ACTIF RÉPUBLICAIN EUROPÉEN)
RÉINVENTONS ASNIÈRES
AIMER NANCY
MOUVEMENT POUR L'ALTERNANCE POLITIQUE
LA ROCHELLE AVENIR
GÉNÉRATIONS ANGOULÊME
NOUVEL ÉLAN "POUR UNE CITOYENNETÉ ACTIVE"
SÈVRES A VENIR - LA BOITE A IDÉES SÉVRIENNE
NANTERRE ENSEMBLE
SOLIDARITÉS 21e, POUR UNE RECOMPOSITION VRAIMENT A GAUCHE DE LA GAUCHE EUROPÉENNE
RÉSEAU-IDENTITÉS
LE TOUQUET DE DEMAIN
OBJECTIF RÉUNION
SENS COMMUN
EUROPE POPULAIRE EUROPOP
UNION POPULAIRE RÉPUBLICAINE
ENSEMBLE, MOUVEMENT POUR UNE ALTERNATIVE DE GAUCHE ÉCOLOGISTE ET SOLIDAIRE
PROMELEC
FRANCE UNIE
ALLIANCE SOLIDAIRE DES FRANÇAIS DE L'ÉTRANGER
RASSEMBLEMENT ET DIVERSITÉ
DROIT AU CŒUR
LES AMIS DE YANNICK MOREAU
ENSEMBLE IMAGINONS DEMAIN
LE MOUVEMENT POUR LA PROSPÉRITÉ ÉCONOMIQUE ET SOCIALE
LA BOÎTE À IDÉES - UMP
BRETAGNE, NOUVELLE VAGUE !
L'OLIVIER, NOUVEAU PAYS CATALAN
LE CERCLE DU COTENTIN
ENTREZ EN RÉSISTANCE
LE PARTI DES LODÉVOIS
NOUVELLE ÉNERGIE
POISSY DE TOUTES NOS FORCES
CITOYENNETÉ ET TERRITOIRES
RASSEMBLEMENT POUR LA RÉUNION
PROXIMITÉ, INITIATIVES, CITOYENNETÉ
G21
UNION RÉPUBLICAINE DE DROITE
ASSOCIATION PLOËRMEL NOUVEL ÉLAN
OXYGÈNE
LA FORCE DU 13
PARTI D'UNION POUR L'AVENIR DE MANTES LA JOLIE
CAR CHÂTEAUDUN ACTIONS RENOUVEAU
LA DROITE POPULAIRE - LA FRANCE EN TÊTE
LES RÉPUBLICAINS
AGIR ENSEMBLE POUR LES LEVALLOISIENS
ALLIANCE ÉCOLOGISTE INDÉPENDANTE
LES AUTHENTIQUES
MOUVEMENT DES PROGRESSISTES
PARTI DE L'ÉMANCIPATION DU PEUPLE (devenu PARTI DE LA DÉMONDIALISATION)
S.I.E.L. - SOUVERAINETÉ, IDENTITÉ ET LIBERTÉ
POUR LA RÉUNION
LIBERTÉ-ÉGALITÉ-MARSEILLAIS
LA RÉUNION EN ACTION
LA FRANCE JUSTE
MOUVEMENT POPULAIRE CALÉDONIEN
CAP 21 - LE RASSEMBLEMENT CITOYEN
FAIRE FRONT
DEMAIN EN MOUVEMENT
UNE NOUVELLE VOIX POUR L'ILE-DE-FRANCE
DEMAIN AUTREMENT POUR VOUS
NANCY VILLE HUMAINE
RENNES ALTERNANCE 2020
TOULOUSE MÉTROPOLE ENSEMBLE
UNSO 94
GRENOBLE HORIZON 2020 (GH.2020)
MOUVEMENT ALSACIEN UNSER LAND
UNION NATIONALE RÉPUBLICAINE ET LAIQUE
LA MANIF POUR TOUS
PLUS BELLE L'HAŸ ENSEMBLE
100 % CENTRISTES
L'AVANT-GARDE
RÉCONCILIATION NATIONALE
MONTAUBAN EN MARCHE
CELLES ET CEUX
PHG
LA RELÈVE RÉPUBLICAINE
ALLONS ENFANTS, LE PARTI DE LA JEUNESSE
MOUVEMENT POUR LE MÂCONNAIS - PASSIONNÉMENT
LE CERCLE DES AMIS DE JÉRÔME VIAUD
GÉNÉRATION CITOYENS
DYNAMIQUE CITOYENNE
ENSEMBLE AVEC GRÉGOIRE DE LASTEYRIE
NEUILLY EN MOUVEMENT
CORSICA LIBERA
ÉCOLOGISTES !

In [46]:
accent_mapping = {
    'à': 'a', 'â': 'a', 'ä': 'a', 'å': 'a',
    'ç': 'c',
    'é': 'e', 'è': 'e', 'ê': 'e', 'ë': 'e',
    'î': 'i', 'ï': 'i',
    'ô': 'o', 'ö': 'o',
    'ù': 'u', 'û': 'u', 'ü': 'u',
    'ÿ': 'y'
}

In [47]:
def name(value):
    regex=r'\([^)]*\)'
    val=re.sub(regex,'',value).lower()
    reg_acc=r'[àâäåçéèêëîïôöùûüÿ]'
    def substitution(match):
        return accent_mapping[match.group(0)]

    # Remplacer les lettres accentuées
    res = re.sub(reg_acc, substitution, val)
    return res

In [48]:
fin['nom parti']=fin['nom parti'].apply(name)

In [49]:
fin[fin['nom parti']=='union des democrates et independants']

,num parti,nom parti,année,immobilisations incorporelles,écarts d'acquisition,terrains et constructions,autres immobilisations corporelles,participations et créances rattachées,prêts à des partis ou groupements politiques,autres immobilisations financières,...,dévolutions de l'excédent des comptes de campagne,dévolutions de partis ou groupements politiques,prestations de services (manifestations et colloques),"ventes de marchandises, productions vendue (biens et services), production stockée et production immobilisée",total iii,total v,"reprise sur amortissements, dépréciations, provisions et transferts de charges",total des produits (i + iii + v),excédent ou déficit d'ensemble,total flux
1447,709,union des democrates et independants,2013,0,0,0,118523,0,0,112650,...,0,1851000,70407,4005,0,39688,0,2247660,-108493,4603813
1761,709,union des democrates et independants,2014,4398,0,265003,56575,455,0,86787,...,13398,1779305,43547,268193,0,10223,0,2463561,-313819,5240941
2074,709,union des democrates et independants,2015,51589,0,232682,38142,0,0,87451,...,2709,2647708,33866,21468,2,58441,0,3432606,424171,6441041
2392,709,union des democrates et independants,2016,33752,0,200360,24628,505,1000,87334,...,0,2216117,52254,102972,10,64117,0,2983669,612905,5354433
2750,709,union des democrates et independants,2017,0,0,169968,14860,505,0,87334,...,5495,2251679,18333,100550,766798,30000,0,3498973,804654,6193292
3139,709,union des democrates et independants,2018,0,0,140239,15242,505,0,90231,...,65,0,3200,148127,176,22066,395109,3593001,256937,6929065
3556,709,union des democrates et independants,2019,0,0,0,146024,419,0,90231,...,0,0,2315,159512,680,1709,2432862,5753696,-1047968,12555360
4036,709,union des democrates et independants,2020,0,0,0,111728,3505,0,111231,...,0,0,75200,161166,401,458,0,3344582,935367,5753797
4525,709,union des democrates et independants,2021,1521,0,0,109891,3505,0,114231,...,0,0,13357,263951,324,0,67180,3538250,735512,6340988
5040,709,union des democrates et independants,2022,988,0,0,87188,3504,0,115832,...,0,0,85428,148451,30604,171,41833,3419648,466945,6372350

In [50]:
partis2=set(fin['nom parti'].unique())
print(partis2)

{"agissons - groupement d'initiative politique", "l'alliance pour le bethunois", "force d'avenir", 'citoyens impliques', 'rassemblement pour une europe ecologiste', 'le chene', "l'union republicaine et d'actions communautaires", 'rassemblement pour levallois', 'les amis du maire de nice', "te'avei'a", 'liberte et progres', 'centre national des independants et paysans', 'union democrate bretonne', 'un nouvel avenir pour villedieu', 'avenir social-democrate ecologiste', 'solidarites 21e, pour une recomposition vraiment a gauche de la gauche europeenne', 'le mouvement des scarabees', 'la diagonale', 'az ais', 'union pour la democratie et la prosperite', 'avec blm', "desirs d'avenir", 'beauchamp renouveau', 'bien vivre dans le drouais', 'mobilises pour le tarn et garonne', 'unissons-nous pour chevilly-larue', 'le parti des travailleurs', 'grenoble 2014', 'groupement france-reunion', 'parti communiste reunionnais', 'association pour la reforme', 'muret au cœur', 'corsica libera', 'regions et peuples solidaires', 'la republique solidaire - lares', 'la releve citoyenne', 'mouvement republicain et citoyen', 'te ora api o porinetia', 'a here ia porinetia', "terres d'echanges", 'liberte citoyenne', "l'union pour la savoie", 'tarbes 2014', "ia ora te nuna'a", 'vivement demain', 'vivre mieux', 'mouvement alsacien unser land', 'les republicains', 'union pour le val de marne - christian cambon', 'union pour saint-sebastien-sur-loire', 'roubaix avenir', 'filoche 2017', 'pour la bretagne !', 'unis pour villeurbanne', 'la martinique ensemble', 'le trefle-les nouveaux                                                                                    ecologistes-homme nature animaux', 'le pole des reformateurs', 'association des amis de cedric villani', 'la voix de la reunion', '100% asnieres', 'vivre a sceaux', 'la vendee pour vous !', 'entente republicaine de nice', "groupe politique l'avenir ensemble", 'ecrivons une nouvelle page ', 'nouveau centre', 'union rosneenne d’action municipale', 'le bon sens en puisaye', 'aspm reims!', 'mouvement citoyen regional nord-pas-de-calais', 'rassembler pour une ile vivante', 'dunkerque en mouvement', "savoie d'aujourd'hui", 'alternative 2007', 'gaillac au cœur', 'grenoble est a vous', 'agir pour nos idees', "l'action", "l'union pour la democratie francaise", 'alliance centriste', 'reussir ensemble en perigord', 'pour pertuis autrement', 'confederation nationale des independants et patriotes', 'la manufacture des idees', 'place publique', "de l'oxygene pour la republique", "l'anjou en action", 'ensemble guyane', 'innover', 'mouvement national republicain', 'parti de gauche', 'vendecologie', "reussir l'avenir avec robin pretot", 'avec', "union pour le val-d'oise", 'dynamique', 'socarrieres', 'la courneuve ensemble !', 'revolution ecologique pour le vivant', 'les progressistes.fr', 'reussir ensemble chilly mazarin', 'debout les socialistes ! - courant du parti socialiste ', 'unir pour lyon avec les equipes de charles million', 'agir ensemble', 'pessac avenir', 'entente republicaine-le parti azureen', 'le parti des lodevois', 'decidemos', 'alternances parisiennes', 'mouvement radical ', "l'union pour les lorientais", 'ambitions pour gap', "libres, republicains et independants d'ile-de-france", 'ensemble pour une sociale ecologie', 'republique solidaire ', "association de soutien a l'action de jean francois lamour", 'forum europeen clermont-ferrand auvergne', 'le mouvement', 'creil ambitions partagees 2020', 'mouvement citoyen regional nord pas de calais', 'rassemblement des ecologistes pour le vivant', 'gauche anticapitaliste', 'les amis de damien abad', 'saint-michel-gauche-avenir', 'futurs-mouvement des refondateurs communistes', 'parti republicain solidariste-forces laiques', 'la droite de progres', "l'union des non inscrits", 'oxygene', "parti d'union pour l'avenir de mantes-la-jolie", 'aspres avenir', 'reseau-identites', 'alliance ecologiste independante', 'association paris 15', "saint-ouen-l'aumone, une ville qui avance", 'la parole au peuple', 'union pour la viieme', 'droit de chasse', "l'alliance ecologiste independante", 'le kremlin-bicetre en avant', 'objectif france', 'rassemblement pour la guadeloupe', 'les amis de lionel royer-perreaut', 'entrez en resistance', 'la france insoumise', 'les commettants', 'les amis de nkm', 'alternative liberale', 'droit au cœur', 'proximite, initiatives, citoyennete', 'ecologistes !', 'la droite citoyenne', 'energies citoyennes', 'maison commune', 'la politique autrement', 'ai\'a.-api "terre nouvelle"', 'generations allauch', 'pour toulouse', 'saint-paul a cœur', "l'alliance centriste", 'france ecologie', 'herblay avec vous', 'agir ensemble pour viry-chatillon', "mon parti c'est joue les tours", 'perspectives lyon et metropole', 'toulouse idees neuves', 'reinventons asnieres', "suresnes j'aime ma ville", 'la france en action', 'les voix de la colere', 'la federation de citoyen-ne-s et de forces pour une alternative sociale et ecologique', 'saint mitre en vie avec vincent goyet', 'renaissance a gauche', 'union des republicains', 'unir nos forces pour nos villes', "une nouvelle voix pour l'ile-de-france", 'demain autrement pour vous', 'union pour un diamant solidaire', 'parti animaliste', 'ambition, audace et avenir', 'rassemblement des citoyens pour la republique', 'mouvement initiative populaire', 'renouveau du service public', 'confluences : lyon nous', 'sucy en mouvement', 'generationfrance.fr', "2022, l'ecologie ! pour une republique ecologique et sociale", 'reussir caen, ensemble', 'paris facile, paris pour tous', 'nous sommes massy', 'democratie et republique ', 'parti du mouvement populaire franciscain', 'car chateaudun actions renouveau', 'ligue du sud', 'union pour le val-de-marne - christian cambon', "ambition citoyenne et solidaire pour l'yonne", 'premieres lignes', 'mouvement ansanm', "l'association murs-erigne, ensemble", "pour l'aquitaine", "non a la turquie dans l'europe", 'parti bonapartiste', 'parti anti-sioniste', 'sevres a venir - la boite a idees sevrienne', "l'entente citoyenne", 'un avenir pour chatillon', 'association des amis de laurence trastour-isnart - aalti', 'alternative democratie socialisme', "l'union pour la viieme", 'batir le pays martinique', 'equinoxe', 'mouvement ecologiste independant', 'ensemble crosne encore et toujours', 'liberons le potentiel de vitry-sur-seine', 'au cœur de thiais', 'rassemblement pour joue', 'mouvement departementaliste mahorais', 'vivons vernaison', 'parti communiste revolutionnaire de france', 'union pour le pays malouin', "l'avenir de chilly-mazarin", 'les republicains-ensemble dans la france', 'association 6eme union', 'peyi guyane', 'generation.s', 'alliance mediterranee alpes ', "l'engagement", 'agir pour le bassin minier', 'le peuple aux commandes du territoire', "groupe d'etudes municipales d'eure et loir", 'grenoble en grand\ngrenoble en grand', 'le mouvement conservateur', "union pour l'avenir du xvieme sud", 'action savoie premiere', 'adecslor', "a gauche, besoin d'optimisme", 'notre france', 'ecologie au centre', "l'association de soutien a l'action de nicolas sarkozy", 'les amis de patrick de carolis', "collectif ecolo et social d'issy", 'territoires 44', 'soutien a alain ravanello', 'reussir ensemble en dordogne-perigord', 'nation, republique, territoire', 'draguignan pour tous', "l'association 6eme union", 'femu a corsica', 'parisiennes, parisiens', 'le 12eme en action', 'generation rillieux-generation renouveau', 'france moderne', "la france c'est vous", 'peyi-a', "l'union pour chatillon", "nouvelle ambition lisieux pays d'auge", "le groupe de reflexion pour l'avenir et l'unite ", "l'alliance regionale", 'socialisme en pays salonais', 'tous rochelais', 'association saint-cyr au cœur', 'alliance pour la guadeloupe', "caudebec c'est vous !", 'mouvement independant populaire', 'idees-force', 'citoyens de la reunion en action ', 'generation ecologie - les bleus', 'dialogue & initiative', 'nouvelle force de guyane', 'les amis de guillaume peltier', 'chasse peche nature et traditions', 'avec vous pour magny', 'agir pour le canton de trelissac', 'mouvement politique forces territoires', 'union gaulliste sociale pour les colombiens "ugasco"', 'le rassemblement ', 'union citoyenne pour montpellier et ses environs', "association de soutien a l'action d'eric woerth", 'blanc-federation', 'mouvement pour le maconnais - passionnement', 'association o.l', 'nouveaux horizons', 'isere premiere', 'etee', 'front national', 'association des objecteurs de croissance', 'mouvement des citoyens ', "unoin des victimes de l'etat", 'passionnement rosny', "rassemblement pour la france et l'independance de l'europe", 'le centre pour la france', "l'union pour l'aveyron", 'saint-maur avenir', 'metz moselle 21eme', 'domoun solidaires et responsables ', 'marseille engagee', 'acu association des communistes unitaires', "j'agis j'innove pour joinville-le-pont", 'ensemble pour nogent', 'union pour saint sebastien sur loire', 'mouvement pour la france', "union des victimes de l'etat sos - seniors", 'union centriste democrate', '100% paris', 'reze citoyenne', 'paris demain', 'pour mulhouse', "fiers d'hesdin", 'union des democrates europeens, centristes et independants', 'bien commun pour gentilly', 'chasse peche nature traditions', "association pour l'avenir de la haute saintonge et de la saintonge atlantique ", 'association les elus angers pour vous', 'liberte-egalite-marseillais', 'vitry rassemble', 'parti republicain chretien', 'la droite sociale', 'mouvement social et liberal de normandie', 'le mouvement de la diversite', 'bretagne, nouvelle vague !', "parti de l'emancipation du peuple ", "l'avenir ensemble ", 'aimer nancy', 'association ploermel nouvel elan', 'changeons villeurbanne', 'france democratie', 'conflans en avant!', 'ensemble pour gonesse', "radicaux de gauche et citoyens d'occitanie", 'kairos-etxea', 'la france audacieuse', 'convergences-gilles carrez', 'le trefle-les nouveaux ecologistes-homme nature animaux', "parti d'union pour l'avenir de mantes la jolie", 'debout la france', 'faire ville ensemble', 'les democrates', "mieux vivre en val d'oise", 'parti socialiste guyanais', 'morbihan en mouvement', 'libres !', "plus belle l'hay ensemble", 'demains', 'atelier libre et responsable', 'citoyennete et territoires', 'rassembler pour agir', 'solidarite 21e, pour une recomposition vraiment a gauche de la gauche europeenne', 'la france juste', "fiers d'etre remois", 'agir, la droite constructive', 'levallois au cœur', "association de soutien a l'action de benoist apparu", 'union des forces citoyennes et republicaines', 'rassemblement et diversite', "dijon c'est capitale", 'ia hau noa', 'parti europe democratie esperanto france', 'union democratique bretonne', 'vision 13', 'via/la voie du peuple', 'parti douce france - pdf', 'rassemblement democratique pour la martinique', "l'union pour muret", 'notre avenir a tous', 'besancon maintenant', 'ile de france en commun', "l'etoile", 'villeurbanne a tout cœur', 'vivre ensemble pour letarn', 'droite sociale reunionnaise', 'unis pour servir', 'palaiseau a venir', 'citoyennete action participation pour le 21eme siecle', "ensemble pour l'eure", 'pour le 5e arrondissement', 'reseau citoyen de grenoble', 'tous dionysiens', "union pour l'aveyron", 'pacte pour la justice sociale et ecologique', "a gauche besoin d'optimisme", 'resistons !', 'union pour strasbourg', "moutiers aujourd'hui et demain", 'les citoyens', 'union democratique pour la liberte egalite et fraternite', 'la france demain', 'eaj-pnb-k aurkeztu hautagaien diruztatze elkartea', 'association psle - nouveau centre', 'caledonie ensemble', 'montauban en marche', 'generation engagement', 'democratie et liberte', 'g21', 'la france qui ose', 'gauche democratique et sociale', 'defi republicain', 'droitelib', 'horizon pour vous', 'la reunion citoyenne', 'nous sommes la metropole', 'cap 21 - le rassemblement citoyen', "marseille d'abord", 'comite pour saint-michel', 'avec-nantes association de veille ecologiste et citoyenne-nantes', 'construire demain !', 'euskal herria bai', 'mouvement democratique alsacienne', 'participation citoyenne', 'nouvel oxygene', "d'agir au quotidien avec nicolas dupont-aignan", 'renouveau en yvelines', 'reconciliation nationale', 'parti chretien-democrate', 'generations vernon, un nouveau souffle pour notre ville !', 'les etats generaux de la renovation 38', 'avenir marseille 11-12', 'mouvement marseille a cœur', 'bougeons nous', "l'union pour l'albigeois", "l'avenir ensemble", 'a droite ! les amis d’eric ciotti', 'ile-de-france rassemblee ', 'aimer charly', 'en avant le 13e', "j'aime chatillon", 'fonsorbes citoyennete', "no oe e te nuna'a", 'courage republique', 'chambery autrement', 'les amis de max-andre pick', 'forum europeen massif central - centre france', 'rassemblement pour la solidarite et la democratie', 'mouvement des citoyens francais de nouvelle caledonie', 'nouvelle donne', 'generation chalon', 'agissons pour la france', 'agir pour colombes', 'pour courdimanche', 'nouvelle energie', 'association ambition reunion', 'osons midi-pyrenees', 'action tank', 'picardie debout !', 'morbihan en transition', 'esprit bordeaux', "l'ecologie autrement", 'les progressistes\xa0.fr', 'convergences nationales', 'la reunion en action', 'union des centristes et des ecologistes', 'debout la republique', "alternance pour l'ile de france", 'ensemble avec gregoire de lasteyrie', "dijon l'avenir ensemble", 'refondation republicaine', 'amicale republicaine des maires', 'a.g.i.r.', 'alyans nasyonal gwadloup', 's.i.e.l. - souverainete, identite et liberte', 'ensemble pour construire', 'ligue communiste revolutionnaire', 'fonsorbes citoyennete 2000', 'saint-michel gauche avenir', '100% savoie', 'la gauche moderne', 'forum republicain', 'association de soutien aux elus de la majorite municipale - asemm', 'chateaudun actions renouveau', 'bastir occitanie', 'forum democratique', "l'union pour l'avenir du pays de ploermel", 'union des citoyens republicains', 'les amoureux de la france', 'objectif reunion', 'action ile-de-france', 'la reunion plus verte', "l'autre metropole", 'droite sociale', 'generation saone-et-loire', "l'action avec gilbert meyer", 'osons andresy !', 'generations grand angouleme', 'parti communiste martiniquais', 'oser la france', 'autrement romainville', "l'association pour la reforme", 'mouvement des progressistes', "l'olivier, nouveau pays catalan", 'pour vous pour albi', 'la republique en commun - argenteuil en commun', 'priorite gournay !', 'la force du 13', 'oise au cœur', 'partit occitan', 'la gauche unitaire', 'union des radicaux, centristes, independants et democrates', 'villejuif avec franck le bohellec', 'parti breton', 'palaiseau ensemble', "citoyen pluri'ailes", 'soyons apt !', "l'autre chemin pour la gauche", "o porinetia to tatou ai'a", 'parti liberal republicain', 'comite central bonapartiste', 'comite des citoyens montreuillois', "l'union pour strasbourg", 'agir aux mureaux', "envol - une energie nouvelle pour le val-d'oise", "l'union des victimes de l'etat sos - seniors", 'les patriotes', 'elles marchent !', 'la france droite', 'paris avenir', 'les alternatifs', "l'eveil oceanien ", 'loire-atlantique a gauche', 'pour vivre mieux en savoie', 'le rassemblement citoyen', 'la cooperative sociale,ecologique et citoyenne', 'la releve republicaine', 'union elargie des seniors', 'toulouse metropole ensemble', 'mouvement populaire caledonien', 'ensemble pour la rochelle', 'changer la donne', 'la droite forte', 'le cercle du cotentin', 'ecologie bleue le parti', "envol - une energie nouvelle pour le val d'oise", 'le colylab', 'union pour la france', 'changer pour gagner', 'paris pour les parisiens', 'association politique "dessinons ensemble le mans de demain"', "union pour la defense et l'avenir du 16eme", 'gironde avenir', 'reussir ensemble en dordogne perigord', 'association parti socialiste parti radical de gauche et apparentes', 'ensemble pour lyon', 'generation macon', 'angouleme ambition', 'les verts', 'dynamique citoyenne', 'les amis de julien polat', 'faire respirer', 'jeanne', 'partitu di a nazione corsa', 'association des communistes unitaires', 's.i.e.l. - souverainete, independance et liberte', 'agir pour demain', 'rassemblement republicain pour la france', 'vitry renouveau', 'le touquet de demain', 'parti liberal democrate', 'bonne republique', 'le havre !', 'en commun !', 'energies pour metz !', 'mars - gauche republicaine', 'confederation des ecologistes independants', 'parti des libertes', 'association des amis de eric ciotti', 'agir pour le vesinet', 'des amis de richard mallie', "cercle terre d'yvelines", "rassemblement pour l'independance et la souverainete de la france ", 'mouvement des seine et marnais', 'dissidence francaise', 'nous france', 'possession ecologie solidaire', 'rouge banlieue, les producteurs de ville en seine-saint-denis', "avenir meilleur pour la population de la reunion dans la france et dans l'europe", 'girondins - ensemble citoyens', "te' avei' a", 'sens commun', 'reflaixion', 'haute autorite de la primaire de la droite et du centre 2016', 'citoyens', 'union des republicains de provence', 'mouvement liberal martiniquais', 'agir ensemble pour levallois', 'la force citoyenne', 'parti lorrain', 'vienne avenir', 'mouvement unitaire des droites independantes ', 'reunion avenir une ambition pour la reunion dans la france', 'les ecolos', 'guadeloupe unie solidaire et responsable', 'doullens en grand, doullens ensemble', 'forum des republicains sociaux', 're-unir', 'le rassemblement - les republicains', "per l'avvene", 'la boite a idees - ump', 'ifrap 2012', "changer c'est possible", 'simple', 'parti progressiste martiniquais', '100% vesoul', 'ensemble imaginons demain', "l'acacia", 'ensemble pour le cambresis', 'le droit chemin', 'solidarite et progres', 'nouvel elan "pour une citoyennete active"', "pour l'isere", "amuitahira'a o te nuna'a maohi", 'parti pour la liberation de la martinique', 'allons enfants, le parti de la jeunesse', 'la reunion, en avant', 'union des francais du monde', 'parti de la resistance', 'a strasbourg', 'le parti democrate', 'citoyens!', "l'essonne avec vous", 'association des progressistes, republicains et personnalites de la vie civile de montigny les cormeilles', 'fontenay en commun', "l'idee francaise", "o porinetia to tatou ai' a", 'courbevoie au cœur', 'paris en commun', 'association la gauche debout et insoumise', 'amitie patriotique', 'souffle breton', 'bougeons-nous', 'les sans etiquettes', 'association nationale des amis de nicolas sarkozy', 'forum metropole 2020', 'rassemblement des asnierois independant, solidaires et ouverts', 'les amis de martine vassal', 'positive', 'forces de gauche', 'tahoeraa huiraatira', 'guadeloupe unie socialisme et realites', "une energie pour le val-d'oise", 'initiatives bron metropole', 'alliance citoyenne pour la transition dite a.c.t.', 'collectif engage et responsable pour la ferte -saint-aubin', 'parti progressiste democratique guadeloupeen', 'union citoyenne pour la liberte', 'savoie pour tous', 'primaire populaire', 'les amis de jean-didier berger', 'parti communiste guadeloupeen', 'la manif pour tous', 'mieux vivre a fresnes', 'reveler rennes', 'le cap aj pour la france', 'phg', 'rassemblement respect reunion rrr', 'reconquete !', 'france 2030', 'walwari', "citoyens en action pour l'outre-mer", 'rassemblement ump pour la caledonie dans la republique', 'les amis de richard maillie', 'toulouse pour tous', 'demorun', 'du courage !', 'aimer la france', "prendre un temps d'avance", 'faire gagner le francois', "l'union pour un mouvement populaire", 'le grand paris des citoyens', 'en marche', 'europe populaire europop', 'ensemble, mouvement pour une alternative de gauche ecologiste et solidaire', "l'union des socialistes pour midi-pyrenees", 'le parti des femmes', 'union pour la democratie', 'des citoyens pour grenoble', 'autrement avec christelle', 'generation citoyens', '"c

In [51]:
dep['groupe_sigle']=dep['groupe_sigle'].apply(name)

In [52]:
dep['groupe_sigle'].unique()

array(['union pour un mouvement populaire',
       'socialiste, radical, citoyen et divers gauche', 'non-inscrits',
       'democratie et republique', 'nouveau centre', 'les republicains',
       'socialistes, ecologistes et republicains',
       'union des democrates et independants',
       'radical, republicain, democrate et progressiste',
       'la republique en marche', 'mouvement democrate',
       'parti socialiste', 'nouvelle gauche', 'liberte et territoires',
       'alliance ecologiste independante', 'la france insoumise',
       'union pour la democratie francaise', 'renaissance',
       'rassemblement national', 'europe ecologie les verts', 'horizons',
       'libertes, independants, outre-mer et territoires'], dtype=object)

In [53]:
deput={
    2007:{"union pour un mouvement populaire":321,"nouveau centre":23,'parti socialiste':204,'parti communiste francais':24,'mouvement democrate':4,'mouvement pour la france':2,'debout la france':2,'europe ecologie les verts':3},
    2012:{'parti socialiste':295,'europe ecologie les verts':20,'parti radical de gauche':15,'union pour un mouvement populaire':196,'union des democrates et independants':15,'parti communiste francais':15,'mouvement pour la france':1,'rassemblement national':2,'mouvement democrate':1},
    2017:{'la republique en marche':314,'mouvement democrate':47,'les republicains':100,'union des democrates et independants':35,'parti socialiste':31,'la france insoumise':17,'parti communiste francais':16,'rassemblement national':7,'europe ecologie les verts':6,'debout la france':1},
    2022:{'renaissance':172,'mouvement democrate':48,'horizons':30,'la france insoumise':75,'parti socialiste':34,'europe ecologie les verts':25,'parti communiste francais':22,'rassemblement national':90,'les republicains':62,'union des democrates et independants':6,'debout la france':1}
}

In [54]:
dep

,nom,date_naissance,num_deptmt,num_circo,groupe_sigle,place_en_hemicycle,nb_mandats,mandat_debut,mandat_fin
0,Guy Teissier,1945-04-04,13,6,union pour un mouvement populaire,168.0,4,2007-06-20,2012-06-19
1,Jean Proriol,1934-11-25,43,2,union pour un mouvement populaire,331.0,2,2007-06-20,2012-06-19
2,Sandrine Hurel,1968-08-07,76,11,"socialiste, radical, citoyen et divers gauche",633.0,2,2007-06-20,2012-06-19
3,Arlette Franco,1939-10-01,66,2,union pour un mouvement populaire,145.0,3,2007-06-20,2010-04-01
4,Pierre-Christophe Baguet,1955-05-11,92,9,union pour un mouvement populaire,291.0,2,2007-06-20,2012-06-19
...,...,...,...,...,...,...,...,...,...
2473,Ingrid Dordain,1978-03-18,80,2,renaissance,464.0,0,2023-09-25,2024-06-09
2474,Mereana Reid Arbelot,1970-09-12,987,3,democratie et republique,582.0,0,2023-06-10,2024-06-09
2475,Philippe Emmanuel,1960-06-08,78,10,renaissance,398.0,0,2023-08-21,2024-06-09
2476,René Pilato,1962-08-31,16,1,la france insoumise,520.0,0,2023-01-29,2024-06-09
2477,Denis Bernaert,1964-05-01,78,4,renaissance,404.0,0,2024-02-12,2024-06-09

In [56]:
partis=set(dep['groupe_sigle'].unique())
print(partis)

{'liberte et territoires', 'mouvement democrate', 'radical, republicain, democrate et progressiste', 'nouvelle gauche', 'horizons', 'democratie et republique', 'alliance ecologiste independante', 'union des democrates et independants', 'renaissance', 'socialistes, ecologistes et republicains', 'la republique en marche', 'non-inscrits', 'socialiste, radical, citoyen et divers gauche', 'les republicains', 'la france insoumise', 'union pour un mouvement populaire', 'europe ecologie les verts', 'parti socialiste', 'nouveau centre', 'libertes, independants, outre-mer et territoires', 'union pour la democratie francaise', 'rassemblement national'}

In [57]:
fin['deputes']=0

In [58]:
deput

{2007: {'union pour un mouvement populaire': 321,
  'nouveau centre': 23,
  'parti socialiste': 204,
  'parti communiste francais': 24,
  'mouvement democrate': 4,
  'mouvement pour la france': 2,
  'debout la france': 2,
  'europe ecologie les verts': 3},
 2012: {'parti socialiste': 295,
  'europe ecologie les verts': 20,
  'parti radical de gauche': 15,
  'union pour un mouvement populaire': 196,
  'union des democrates et independants': 15,
  'parti communiste francais': 15,
  'mouvement pour la france': 1,
  'rassemblement national': 2,
  'mouvement democrate': 1},
 2017: {'la republique en marche': 314,
  'mouvement democrate': 47,
  'les republicains': 100,
  'union des democrates et independants': 35,
  'parti socialiste': 31,
  'la france insoumise': 17,
  'parti communiste francais': 16,
  'rassemblement national': 7,
  'europe ecologie les verts': 6,
  'debout la france': 1},
 2022: {'renaissance': 172,
  'mouvement democrate': 48,
  'horizons': 30,
  'la france insoumise': 75,
  'parti socialiste': 34,
  'europe ecologie les verts': 25,
  'parti communiste francais': 22,
  'rassemblement national': 90,
  'les republicains': 62,
  'union des democrates et independants': 6,
  'debout la france': 1}}

In [33]:
deput={
    2007:{"union pour un mouvement populaire":320,"nouveau centre":23,'parti socialiste':204,'parti communiste francais':21,'mouvement democrate':2,'mouvement pour la france':2,'debout la france':2,'europe ecologie les verts':3},
    2012:{'parti socialiste':295,'europe ecologie les verts':20,'parti radical de gauche':15,'union pour un mouvement populaire':196,'union des democrates et independants':15,'parti communiste francais':15,'mouvement pour la france':1,'rassemblement national':2,'mouvement democrate':1},
    2017:{'la republique en marche':314,'mouvement democrate':47,'les republicains':100,'union des democrates et independants':35,'parti socialiste':31,'la france insoumise':17,'parti communiste francais':16,'rassemblement national':7,'europe ecologie les verts':6,'debout la france':1},
    2022:{'renaissance':172,'mouvement democrate':48,'horizons':30,'la france insoumise':75,'parti socialiste':34,'europe ecologie les verts':25,'parti communiste francais':22,'rassemblement national':90,'les republicains':62,'union des democrates et independants':6,'debout la france':1}
}

In [59]:
fin[fin['nom parti']=='mouvement pour la france']['num parti'].unique()[0]

177

In [60]:
for i in deput:
    for j in list(deput[i].keys()):
        print(j)
        num=fin[fin['nom parti']==j]['num parti'].unique()[0]
        deput[i][num]=deput[i].pop(j)

union pour un mouvement populaire
nouveau centre
parti socialiste
parti communiste francais
mouvement democrate
mouvement pour la france
debout la france
europe ecologie les verts
parti socialiste
europe ecologie les verts
parti radical de gauche
union pour un mouvement populaire
union des democrates et independants
parti communiste francais
mouvement pour la france
rassemblement national
mouvement democrate
la republique en marche
mouvement democrate
les republicains
union des democrates et independants
parti socialiste
la france insoumise
parti communiste francais
rassemblement national
europe ecologie les verts
debout la france
renaissance
mouvement democrate
horizons
la france insoumise
parti socialiste
europe ecologie les verts
parti communiste francais
rassemblement national
les republicains
union des democrates et independants
debout la france

In [61]:
deput

{2007: {401: 321, 531: 23, 76: 204, 60: 24, 529: 4, 177: 2, 410: 2, 104: 3},
 2012: {76: 295,
  104: 20,
  52: 15,
  401: 196,
  709: 15,
  60: 15,
  177: 1,
  40: 2,
  529: 1},
 2017: {910: 314,
  529: 47,
  401: 100,
  709: 35,
  76: 31,
  976: 17,
  60: 16,
  40: 7,
  104: 6,
  410: 1},
 2022: {910: 172,
  529: 48,
  1344: 30,
  976: 75,
  76: 34,
  104: 25,
  60: 22,
  40: 90,
  401: 62,
  709: 6,
  410: 1}}

In [62]:
for i in deput:
    for j in deput[i]:
        for k in range(5):
            fin.loc[(fin['année'] == i+k) & (fin['num parti'] == j), 'deputes'] = deput[i][j]

In [64]:
fin['deputes'].unique()

array([  0,  24, 204,   3,   2, 321,   4,  23,  15, 295,  20,   1, 196,
         7,  16,  31,   6, 100,  47,  35, 314,  17,  90,  22,  34,  25,
        62,  48, 172,  75,  30], dtype=int64)

In [65]:
fin

,num parti,nom parti,année,immobilisations incorporelles,écarts d'acquisition,terrains et constructions,autres immobilisations corporelles,participations et créances rattachées,prêts à des partis ou groupements politiques,autres immobilisations financières,...,dévolutions de partis ou groupements politiques,prestations de services (manifestations et colloques),"ventes de marchandises, productions vendue (biens et services), production stockée et production immobilisée",total iii,total v,"reprise sur amortissements, dépréciations, provisions et transferts de charges",total des produits (i + iii + v),excédent ou déficit d'ensemble,total flux,deputes
0,1,democratie et republique,2008,0,0,0,0,0,0,0,...,0,0,0,1905,0,0,186008,-1007,373023,0
1,5,l'alliance regionale,2008,0,0,0,0,0,0,0,...,0,0,0,0,0,0,70921,-781,142623,0
2,13,centre national des independants et paysans,2008,0,0,124651,4982,0,0,840,...,0,88800,1489,27433,0,0,154684,-52223,361591,0
3,17,combat pour les valeurs,2008,0,0,0,0,0,0,30,...,0,0,31386,0,0,0,31686,-14573,77945,0
4,40,front national,2008,24537,0,4198171,741272,14000,717658,93728,...,15000,196224,206599,45986,86966,163809,3854207,-2445426,10153840,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5438,1455,terre d'avenir,2022,0,0,0,0,0,0,0,...,0,0,0,0,0,0,12900,9225,16574,0
5439,1457,100% vesoul,2022,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5440,1464,maison commune,2022,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5441,1473,loire-atlantique a gauche,2022,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5442,1486,reveler rennes,2022,0,0,0,0,0,0,30,...,0,0,0,0,0,0,1031,-501,2563,0

In [71]:
no_dep=fin[fin['deputes']!=0]['num parti'].unique()
clean_fin=fin[fin['num parti'].isin(no_dep)]

In [72]:
clean_fin

,num parti,nom parti,année,immobilisations incorporelles,écarts d'acquisition,terrains et constructions,autres immobilisations corporelles,participations et créances rattachées,prêts à des partis ou groupements politiques,autres immobilisations financières,...,dévolutions de partis ou groupements politiques,prestations de services (manifestations et colloques),"ventes de marchandises, productions vendue (biens et services), production stockée et production immobilisée",total iii,total v,"reprise sur amortissements, dépréciations, provisions et transferts de charges",total des produits (i + iii + v),excédent ou déficit d'ensemble,total flux,deputes
4,40,front national,2008,24537,0,4198171,741272,14000,717658,93728,...,15000,196224,206599,45986,86966,163809,3854207,-2445426,10153840,0
8,52,parti radical de gauche,2008,0,0,76225,74503,0,0,73793,...,418225,22871,95534,18376,234,0,2047197,35293,4059101,0
11,60,parti communiste francais,2008,0,0,6070376,695940,103251,11494547,51696,...,0,777259,1960503,272132,250770,389767,31559485,725272,62393698,24
18,76,parti socialiste,2008,245377,0,14048629,2574300,1348989,1767573,492160,...,89885,739962,3359598,470816,712047,2192099,59166852,17139,118316565,204
27,104,les verts,2008,23465,0,0,2221669,103665,0,401382,...,6000,128265,286247,23892,158579,81592,5166761,439834,9893688,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4988,531,les centristes,2022,431,0,0,0,0,0,8850,...,0,0,0,0,460,11230,440658,14775,866540,0
5040,709,union des democrates et independants,2022,988,0,0,87188,3504,0,115832,...,0,85428,148451,30604,171,41833,3419648,466945,6372350,6
5100,910,renaissance,2022,4590,0,31279266,8847935,0,0,40847,...,3462,44648,201407,16186,0,4796126,34866826,1327646,68406005,172
5128,976,la france insoumise,2022,0,0,0,170928,381,0,190681,...,0,274560,369808,1,28,1748739,7599991,-4761055,19961038,75
5356,1344,horizons,2022,49155,0,0,16062,0,0,0,...,0,0,0,0,0,13296,828988,-173019,1830996,30

In [68]:
no_dep['num parti'].unique()

array([  60,   76,  104,  177,  401,  410,  529,  531,   40,   52,  709,
        910,  976, 1344], dtype=int64)

In [73]:
#dep.to_csv('deputes_reduced2.csv',index=False)
clean_fin.to_csv('fin_reduced2.csv',index=False)